name: .NET Framework

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      with:
        msbuild-version: 4.8
        use-default-credentials: true

    - name: Build
      run: msbuild /p:Configuration=Release ST10085400_PROG7312_POE.sln

    - name: Test
      run: vstest.console.exe bin\Release\ST10085400_PROG7312_POE.dll
