name: .NET

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: warrenbuckley/Setup-NET-Framework@v1
      with:
        net-framework-version: '4.x' # Use '4.x' to target .NET Framework 4.8.0

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /maxcpucount /nologo /v:quiet

