name: Tests

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0

      - name: Setup .NET Framework
        uses: warrenbuckley/Setup-NET-Framework@v1
        with:
          net-framework-version: '4.x' # Use '4.x' to target .NET Framework 4.8.0

      - name: Restore NuGet packages
        run: nuget restore ST10085400_PROG7312_POE.sln

